# BentoBox v1.14.0 配置文件.
# 在此配置文件注释中，addon 翻译为扩展，plugin 翻译为插件
# 
# 你可以在这里设置以下项:
#  * 数据存储方式
#  * 游戏模式 (指令, ...)
#  * 网络连接 (web-based content-enriched 功能, ...)
# 
# 注意这个配置文件是会实时变化的:
#  * BentoBox 读取完此文件后会用最新的设置和注释更新此文件.
#  * 当更新 BentoBox 时, 新设置会自动加到此文件中.
#     * 并会加入像这样的注释:
#        Added since X.Y.Z.
#     * 新设置都是默认值, 一般不会对你的服务器造成影响.
#  * 你可以在服务器运行时编辑此文件.
#    但是你需要执行此命令使其生效: /bentobox reload.
# 
# 这是一些开始之前的建议:
#  * 阅读插件文档, 里面有有用的提示和见解.
#     英文文档链接: https://github.com/BentoBoxWorld/BentoBox/wiki
#     中文文档链接: https://www.mcbbs.net/thread-1009602-1-1.html
#  * 建议在关闭服务器的状态下编辑此文件.
#  * 另外, 在更新 BentoBox 后, 建议先在测试服务器中进行测试.
#     This will allow you to configure the new settings beforehand instead of applying them inadvertently on a live production server.
general:
  # 新玩家的默认语言.
  # 请填写 locales 文件夹中不带 .yml 后缀的文件名.
  # 如果你填写的文件不存在, 将会使用默认的美式英语.
  default-language: zh-CN
  # 是否开启经济功能. 如果开启, 你必须安装一个经济插件. 如果关闭, 插件的任何功能都不会收取或奖励金钱.
  # 如果服务器未安装经济插件, 此项将会自动禁用.
  use-economy: true
  database:
    # JSON, MYSQL, MARIADB, MONGODB, SQLITE, POSTGRESQL 和 YAML(不推荐).
    # 数据库转换选项:
    #   YAML2JSON, YAML2MARIADB, YAML2MYSQL, YAML2MONGODB, YAML2SQLITE
    #   JSON2MARIADB, JSON2MYSQL, JSON2MONGODB, JSON2SQLITE, JSON2POSTGRESQL
    #   MYSQL2JSON, MARIADB2JSON, MONGODB2JSON, SQLITE2JSON, POSTGRESQL2JSON
    # 如果你想使用其它存储方式, 请在 GitHub 上建议.
    # 最低要求:
    #    MySQL 5.7 或更高
    #    MariaDB 10.2.3 或更高
    #    MongoDB 3.6 或更高
    #    SQLite 3.28 或更高
    #    PostgreSQL 9.4 或更高
    # 数据库转换选项用于转换数据库类型时迁移数据. 使用指令 /bbox migrate.
    # YAML 和 JSON 是基于文件的存储类型.
    # MYSQL 可能会在某些平台上出现问题: 如果是这样的话, 请使用专用数据库类型 (如 MARIADB).
    # 如果你在使用 MONGODB, 你必须安装 BSBMongo 插件 (非扩展).
    # 见 https://github.com/tastybento/bsbMongo/releases/.
    # 详细信息见此视频: https://www.bilibili.com/video/BV1ap4y1C7bo/
    type: JSON
    host: localhost
    # 3306 是 MySQL 的默认端口. 27017 是 MongoDB 的默认端口.
    port: 3306
    name: bentobox
    username: username
    password: password
    # 多久保存一次数据到文件中. 默认是 5 分钟.
    # 这可以相对减少服务器崩溃造成的数据丢失.
    # 数据还会在某些重要操作执行时保存.
    backup-period: 5
    # 开启对 MongoDB, MariaDB, MySQL 和 PostgreSQL 的加密连接支持.
    # Added since 1.12.0.
    use-ssl: false
    # 数据表前缀. 若使用文件存储方式请无视此项.
    # 仅允许 A-Z, a-z, 0-9. 其它字符将被替换为下划线(_).
    # 如果你的多个 BentoBox 服务器使用同一个数据库，请务必设置此项.
    # 请注意长度 - 一般不超过63字节.
    # Added since 1.13.0.
    prefix-character: ''
    # MongoDB 客户端连接 URI.
    # 详见: https://docs.mongodb.com/manual/reference/connection-string/
    # Added since 1.14.0.
    mongodb-connection-uri: ''
  # 允许 FTB(https://www.feed-the-beast.com/ 一个 MOD) 模组的自激活仪器(Autonomous Activator)工作 (将会允许虚拟玩家 [CoFH] 放置和破坏方块并拾取物品)
  # 如果需要的话，在这里添加更多虚拟玩家的名字
  # /!\ 此功能仍处于测试阶段，可能不会正常工作.
  fakeplayers:
  - '[CoFH]'
panel:
  # 当玩家点击菜单之外的区域时关闭菜单
  close-on-click-outside: true
  # 菜单空白区域填充的物品.
  # Added since 1.14.0.
  filler-material: LIGHT_BLUE_STAINED_GLASS_PANE
logs:
  # 是否在服务器日志中记录超平坦区块的重新生成.
  # 如果超平坦区块很多的话，它会霸占你的控制台.
  # 但是, 超平坦区块的重新生成非常占用服务器性能, 所以推荐将
  # 此功能打开, 这样会方便你查找服务器卡顿问题的原因.
  # Added since 1.2.0.
  clean-super-flat-chunks: true
  # 从 GitHub 下载数据的行为是否要记录在日志中.
  # Added since 1.5.0.
  github-download-data: true
island:
  cooldown:
    time:
      # 玩家被踢出一个队伍多少分钟后可以再次加入一个队伍.
      # 这可以降低玩家重复进入队伍重复做任务的效率
      invite: 60
      # 玩家需要等多久才能再次与一个玩家合作.
      coop: 5
      # 玩家需要等几分钟才能再次信任一个玩家.
      trust: 5
      # 玩家在解封一个玩家多久后可以再封禁他. 以分钟为单位.
      ban: 10
      # 玩家两次重置岛屿需最少间隔多少秒.
      reset: 300
    options:
      # 岛屿重置限制是否应在玩家第一次创建岛屿时就开始执行.
      # Added since 1.2.0.
      set-reset-cooldown-on-create: true
  confirmation:
    # 玩家需要在多少秒内确认某些重要操作, 如岛屿重置.
    time: 10
    commands:
      # 哪些操作需要再次输入指令确认.
      # 踢出
      kick: true
      # 离开
      leave: true
      # 重置
      reset: true
    # 玩家是否需要确认信任/合作请求.
    # 由于安全原因, 团队邀请始终需要确认.
    # Added since 1.8.0.
    invites: false
  delay:
    # 玩家需要站着不动多少秒后才能触发传送操作, 如 /island go.
    time: 0
  name:
    # 岛屿名最短需要多少个字符.
    min-length: 4
    # 岛屿名最多可以包含的字符数.
    max-length: 20
    # 是否禁止岛屿重名.
    # 如果开启，每个游戏模式的每一个岛屿的名字都必须是不同的.
    # 注意岛屿名并不会被插件用来识别岛屿.
    # Added since 1.7.0.
    uniqueness: false
  # 移除在传送目的地多少范围内的敌对生物
  # 如果敌对生物已清除，玩家周围的火柴盒就会被移除
  # 如设为 5 将会在玩家周围搭起 10 x 10 x 10 的火柴盒
  # 尽量不要设太大. 此项不影响末地和下界的传送.
  # Added since 1.6.0.
  clear-radius: 5
  # 粘贴蓝图的速度(多少方块/tick).
  # 值越小，对服务器的影响越小，但是粘贴时间会加长.
  # 过大的值可能导致服务器崩溃
  paste-speed: 64
  # 删除岛屿的速度(多少区块/tick/世界).
  # 设为 0 将保留岛屿方块 (不推荐).
  # Added since 1.7.0.
  delete-speed: 1
  deletion:
    # 玩家重置岛屿时是否清除旧岛.
    # * 如果设为 'true', 当玩家重置岛屿时, 旧岛将会保留且变为未领取状态.
    #   但是你仍然可以以后清除它们.
    #   如果你的服务器规模较大, 这会导致世界体积变大.
    #   然而这将允许管理员恢复一个玩家的岛屿.
    #   管理员也可以为旧岛设置所有者.
    # * 如果设为 'false', 当玩家重置岛屿时, 旧岛就会被删除.
    #   这是默认的值.
    # Added since 1.13.0.
    keep-previous-island-on-reset: false
web:
  github:
    # 是否允许 BentoBox 连接 GitHub 获取更新和扩展.
    # 禁用此功能将导致更新检测不可用并将禁用依赖 GitHub 数据的功能.
    # 插件不会发送任何信息.
    # Added since 1.5.0.
    download-data: true
    # 连接到 GitHub 服务器的间隔, 以分钟为单位.
    # 这样有助于收集最新信息.
    # 但是由于 GitHub API 不会实时更新数据, 所以此值不得少于 60 分钟.
    # 设为 0 禁用(仅在启动时连接).
    # Added since 1.5.0.
    connection-interval: 120
